### ISSUE TITLE
Introducing user database

### ISSUE THREAD

**Issue by IvoryTower48** [lore157/stock_market#12]
We need to have a working database that allows users to register and login to use our program.
In particular, the program should:
- be able to open the database correctly or, if it's empty, create the necessary tables;
- allow users to register themselves in our database;
- allow users to login in order to use the program;
- use salted hashing for protecting stored passwords. Eventually, introduce other security measures.

**Comment by M-PETT** [comment]
I have implemented the Open_and_create function, on 80d96fed44519ca9ba630b765a13aac3830a420b
Now i'm working on the other ones

**Comment by IvoryTower48** [comment]
I successfully made the registration function work, and the password is correctly salted too, at cff203da0eb7ba0946e36d033873c752bd17f724 . Focus on fixing the check_for_username function, it's still broken as hell.

**Comment by IvoryTower48** [comment]
Basic functionalities of the database are complete. Closing. 6aa411693a959f528cf56030f554f0dc5dc0a302
